spring:
  datasource:
    url: jdbc:mysql://localhost:3306/solumon?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
  jwt:
    secretKey: 
  redis:
    host: localhost
    port: 6379
kakao-rest-api-key: 
kakao-admin-key: 
